### ISSUE TITLE
Not working behind a proxy

### ISSUE THREAD

**Issue by bheisig** [anas-aso/ssllabs_exporter#40]
Since version `0.4.0` it's not possible to start the exporter behind a proxy. Output using Docker:

~~~
panic: failed to initialize API client. this should never happen!

goroutine 1 [running]:
github.com/anas-aso/ssllabs_exporter/internal/ssllabs.init.0()
        /workdir/internal/ssllabs/analyze.go:34 +0x74
~~~

`Dockerfile`:

~~~
FROM anasaso/ssllabs_exporter:latest
ENV http_proxy http://proxy.example.com
ENV https_proxy http://proxy.example.com
ENV HTTP_PROXY http://proxy.example.com
ENV HTTPS_PROXY http://proxy.example.com
~~~

Commands:

~~~
docker build . -t ssllabs:test
docker run --rm -it -p 19115:19115 ssllabs:test
~~~

It's working with version `0.3.0` instead of `latest`. I've tested versions `0.4.1` and `0.4.0`, too. But no luck.

Latest version is working fine on another environment without a proxy.

Thanks for you help.

**Comment by anas-aso** [comment]
a "bit" delayed, but I believe this issue has been fixed in https://github.com/anas-aso/ssllabs_exporter/pull/38

**Comment by bheisig** [comment]
Unfortunately, the issue is still reproducible with `v0.6.0`.
